"""Actual NIFTY Midcap 100 constituents (as published 2 Sep 2026).

Unlike a hand-built list, this includes distressed names (YESBANK, IDEA,
SUZLON, PAYTM) that a survivor-biased selection would silently omit.
"""
NIFTY_MIDCAP100 = [
 "360ONE","ATGL","ABCAPITAL","ALKEM","APLAPOLLO","ASHOKLEY","ASTRAL","AUBANK",
 "AUROPHARMA","BANKINDIA","BDL","BHARATFORG","BHEL","BIOCON","BLUESTARCO","BSE",
 "COCHINSHIP","COFORGE","COLPAL","CONCOR","COROMANDEL","DABUR","DIXON","EXIDEIND",
 "FORTIS","NYKAA","GVT&D","GLENMARK","GMRAIRPORT","GODFRYPHLP","GODREJPROP",
 "HAVELLS","HEROMOTOCO","HINDPETRO","POWERINDIA","HUDCO","ICICIGI","IDFCFIRSTB",
 "INDIANB","IRCTC","IREDA","INDUSTOWER","INDUSINDBK","NAUKRI","JSWENERGY",
 "JUBLFOOD","KALYANKJIL","KEI","KPITTECH","LTF","LAURUSLABS","LICHSGFIN","LUPIN",
 "M&MFIN","MANKIND","MARICO","MFSL","MOTILALOFS","MPHASIS","MRF","MCX","NATIONALUM",
 "NHPC","NMDC","OBEROIRLTY","OIL","PAYTM","OFSS","PAGEIND","PATANJALI","POLICYBZR",
 "PERSISTENT","PIIND","POLYCAB","PREMIERENE","PRESTIGE","RADICO","RVNL","SBICARD",
 "SRF","SAIL","SUPREMEIND","SUZLON","TATACOMM","TATAELXSI","TATAINVEST","FEDERALBNK",
 "PHOENIXLTD","TIINDIA","UPL","IDEA","VOLTAS","WAAREEENER","YESBANK",
]
