"""NIFTY 100 constituents (approximate, current). Yahoo tickers add .NS"""
NIFTY100 = [
    "RELIANCE","TCS","HDFCBANK","ICICIBANK","INFY","HINDUNILVR","ITC","SBIN","BHARTIARTL",
    "KOTAKBANK","LT","HCLTECH","AXISBANK","MARUTI","ASIANPAINT","SUNPHARMA","TITAN",
    "ULTRACEMCO","BAJFINANCE","WIPRO","NESTLEIND","ONGC","NTPC","POWERGRID","M&M",
    "TATAMOTORS","TATASTEEL","JSWSTEEL","HINDALCO","COALINDIA","GRASIM","TECHM","ADANIENT",
    "ADANIPORTS","BAJAJFINSV","DRREDDY","CIPLA","EICHERMOT","BRITANNIA","HEROMOTOCO",
    "DIVISLAB","BPCL","INDUSINDBK","APOLLOHOSP","TATACONSUM","SBILIFE","HDFCLIFE",
    "BAJAJ-AUTO","SHRIRAMFIN","LTIM","PIDILITIND","GODREJCP","DABUR","MARICO","HAVELLS",
    "SIEMENS","DLF","AMBUJACEM","BANKBARODA","PNB","CANBK","IOC","GAIL","VEDL","JINDALSTEL",
    "SAIL","NMDC","TATAPOWER","ADANIGREEN","ADANIPOWER","TORNTPHARM","LUPIN","AUROPHARMA",
    "BIOCON","ZYDUSLIFE","ALKEM","MOTHERSON","BOSCHLTD","TVSMOTOR","ASHOKLEY","BHARATFORG",
    "CUMMINSIND","ABB","BEL","HAL","BHEL","IRCTC","INDIGO","TRENT","DMART","NAUKRI",
    "ZOMATO","PAYTM","POLICYBZR","MUTHOOTFIN","CHOLAFIN","ICICIGI","ICICIPRULI","LICI",
    "SBICARD","BERGEPAINT","COLPAL","UBL","MCDOWELL-N","PAGEIND","PEL","UPL","SRF",
]
